### ISSUE TITLE
Doesn't continue running / possibly creating video

### ISSUE THREAD

**Issue by QuinnLawson** [genixpro/kwola#6]
Terminal: 

  "success": true,
    "testingStepId": "d4if_testing_step_6"
}
Traceback (most recent call last):
  File "/home/bradley/venv/bin/kwola", line 8, in <module>
    sys.exit(main())
  File "/home/bradley/venv/lib64/python3.7/site-packages/kwola/bin/main.py", line 181, in main
    TrainAgentLoop.trainAgent(configDir)
  File "/home/bradley/venv/lib64/python3.7/site-packages/kwola/tasks/TrainAgentLoop.py", line 259, in trainAgent
    runMainTrainingLoop(config, trainingSequence, exitOnFail=True)
  File "/home/bradley/venv/lib64/python3.7/site-packages/kwola/tasks/TrainAgentLoop.py", line 208, in runMainTrainingLoop
    raise RuntimeError("One of the testing / training loops failed and did not return successfully. Exiting the training loop.")
RuntimeError: One of the testing / training loops failed and did not return successfully. Exiting the training loop.

**Comment by genixpro** [comment]
Hello Quinn, thank you for this posting. Can you please provide more context on the error that occurred? Which URL did you run the algorithm on? And could you also paste a larger amount of the terminal output from Kwola?

**Comment by QuinnLawson** [comment]
URL: https://s.app.joinlane.com/login

Issue: The folders are empty. No bugs. No videos folder.

Terminal:

[bradley@therig ~]$ source venv/bin/activate
(venv) [bradley@therig ~]$ kwola https://s.app.joinlane.com/login
Verifying your Kwola installation ... Please wait a moment
Everything in your Kwola installation appears to be working! Excellent.
? Which configuration do you want to load for your model?  medium

? What is the email/username you want to use (blank disables this action)?
quinn
@kwola.io

? What is the password you want to use (blank disables this action)?
kwola123
? What is the human name / short text you want to use (blank disables this
actio
n)?

? What is the paragraph / long text you want to use (blank disables this
action)
?

? Please select which commands you want to enable  done

? Do you want to tune any configuration settings in your Kwola run before
procee
ding?  no

? Are you ready to unleash the Kwolas?  yes


Starting a fresh Kwola run in directory kwola_run_005 targeting URL
https://s.app.joinlane.com/login

2020-04-23 18:33:43.155264 [76944] Starting up 1 parallel browser sessions.
2020-04-23 18:33:46.134313 [76944] Successfully translated pay.js with
Kwola branch counting and event tracing.
2020-04-23 18:33:49.480300 [76944] Successfully translated
vendor.6d430edf6254318533de.js with Kwola branch counting and event tracing.
2020-04-23 18:33:51.600437 [76944] Successfully translated
main.29a63bee3322775ee43c.js with Kwola branch counting and event tracing.
2020-04-23 18:34:04.763733 [76944] Successfully translated
m-outer-5af13a74058f4fb832e146db610e8300.js with Kwola branch counting and
event tracing.
2020-04-23 18:34:06.435583 [76944] Successfully translated common.js with
Kwola branch counting and event tracing.
2020-04-23 18:34:06.953799 [76944] Successfully translated util.js with
Kwola branch counting and event tracing.
2020-04-23 18:35:15.564051 [76944] Error! Unable to install Kwola
line-counting in the Javascript file common.cc1d895e245b691c9cb0.js. Most
likely this is because Babel thinks your javascript has invalid syntax, or
that babel is not working / not able to find the babel-plugin-kwola /
unable to transpile the javascript for some other reason. See the following
truncated output:
b'\n<--- Last few GCs --->\n\n[81663:0x55bc9f76daf0]    59342 ms: Scavenge
1377.7 (1422.4) -> 1377.1 (1422.9) MB, 4.8 / 0.0 ms  (average mu = 0.176,
current mu = 0.140) allocation failure \n[81663:0x55bc9f76daf0]    59349
ms: Scavenge 1378.0 (1422.9) -> 13'
b'FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed
- JavaScript heap out of memory\n 1: 0x7f2895294f2c node::Abort()
[/lib64/libnode.so.64]\n 2: 0x7f2895294f75  [/lib64/libnode.so.64]\n 3:
0x7f28956444ba v8::Utils::ReportOOMFailure'
2020-04-23 18:35:23.088860 [76944] Successfully translated logger.min.js
with Kwola branch counting and event tracing.
2020-04-23 18:35:25.388125 [76944] Starting random testing sequences for
initialization
2020-04-23 18:35:26.807267 [86059] TaskProcess: Waiting for input from stdin
2020-04-23 18:35:26.807378 [86059] Running process with following data:
{
    "configDir": "kwola_run_005",
    "testingStepId": "vwzs_testing_step_0",
    "shouldBeRandom": true
}
2020-04-23 18:35:26.807428 [86059] Starting New Testing Sequence
2020-04-23 18:35:29.851935 [86922] TaskProcess: Waiting for input from stdin
2020-04-23 18:35:29.852034 [86922] Running process with following data:
{
    "configDir": "kwola_run_005",
    "testingStepId": "vwzs_testing_step_1",
    "shouldBeRandom": true
}
2020-04-23 18:35:29.852086 [86922] Starting New Testing Sequence
2020-04-23 18:35:32.789259 [87905] TaskProcess: Waiting for input from stdin
2020-04-23 18:35:32.789384 [87905] Running process with following data:
{
    "configDir": "kwola_run_005",
    "testingStepId": "vwzs_testing_step_2",
    "shouldBeRandom": true
}
2020-04-23 18:35:32.789453 [87905] Starting New Testing Sequence
2020-04-23 18:35:35.818908 [88789] TaskProcess: Waiting for input from stdin
2020-04-23 18:35:35.819007 [88789] Running process with following data:
{
    "configDir": "kwola_run_005",
    "testingStepId": "vwzs_testing_step_3",
    "shouldBeRandom": true
}
2020-04-23 18:35:35.819057 [88789] Starting New Testing Sequence
Traceback (most recent call last):
  File
"/home/bradley/venv/lib64/python3.7/site-packages/kwola/tasks/RunTestingStep.py",
line 117, in runTestingStep
    environment = WebEnvironment(config=config)
  File
"/home/bradley/venv/lib64/python3.7/site-packages/kwola/components/environments/WebEnvironment.py",
line 63, in __init__
    future.result() for future in sessionFutures
  File
"/home/bradley/venv/lib64/python3.7/site-packages/kwola/components/environments/WebEnvironment.py",
line 63, in <listcomp>
    future.result() for future in sessionFutures
  File "/usr/lib64/python3.7/concurrent/futures/_base.py", line 435, in
result
    return self.__get_result()
  File "/usr/lib64/python3.7/concurrent/futures/_base.py", line 384, in
__get_result
    raise self._exception
  File "/usr/lib64/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File
"/home/bradley/venv/lib64/python3.7/site-packages/kwola/components/environments/WebEnvironment.py",
line 49, in createSession
    return WebEnvironmentSession(config, number, self.proxyPort,
self.pathTracer)
  File
"/home/bradley/venv/lib64/python3.7/site-packages/kwola/components/environments/WebEnvironmentSession.py",
line 77, in __init__
    self.driver.get(self.targetURL)
  File
"/home/bradley/venv/lib64/python3.7/site-packages/selenium/webdriver/remote/webdriver.py",
line 333, in get
    self.execute(Command.GET, {'url': url})
  File
"/home/bradley/venv/lib64/python3.7/site-packages/selenium/webdriver/remote/webdriver.py",
line 321, in execute
    self.error_handler.check_response(response)
  File
"/home/bradley/venv/lib64/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py",
line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out
receiving message from renderer: -0.001
  (Session info: headless chrome=80.0.3987.132)

2020-04-23 18:35:27.810169 [86059] Starting up 12 parallel browser sessions.
2020-04-23 18:45:28.507245 [86059] Unhandled exception occurred during
testing sequence
2020-04-23 18:45:28.507307 [86059] Finished Running Testing Sequence!
======== TASK PROCESS RESULT START ========
{"success": false}
======== TASK PROCESS RESULT END ========
2020-04-23 18:45:28.685207 [76944] Terminating task subprocess, task
finished.
Traceback (most recent call last):
  File
"/home/bradley/venv/lib64/python3.7/site-packages/kwola/tasks/RunTestingStep.py",
line 117, in runTestingStep
    environment = WebEnvironment(config=config)
  File
"/home/bradley/venv/lib64/python3.7/site-packages/kwola/components/environments/WebEnvironment.py",
line 63, in __init__
    future.result() for future in sessionFutures
  File
"/home/bradley/venv/lib64/python3.7/site-packages/kwola/components/environments/WebEnvironment.py",
line 63, in <listcomp>
    future.result() for future in sessionFutures
  File "/usr/lib64/python3.7/concurrent/futures/_base.py", line 435, in
result
    return self.__get_result()
  File "/usr/lib64/python3.7/concurrent/futures/_base.py", line 384, in
__get_result
    raise self._exception
  File "/usr/lib64/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File
"/home/bradley/venv/lib64/python3.7/site-packages/kwola/components/environments/WebEnvironment.py",
line 49, in createSession
    return WebEnvironmentSession(config, number, self.proxyPort,
self.pathTracer)
  File
"/home/bradley/venv/lib64/python3.7/site-packages/kwola/components/environments/WebEnvironmentSession.py",
line 77, in __init__
    self.driver.get(self.targetURL)
  File
"/home/bradley/venv/lib64/python3.7/site-packages/selenium/webdriver/remote/webdriver.py",
line 333, in get
    self.execute(Command.GET, {'url': url})
  File
"/home/bradley/venv/lib64/python3.7/site-packages/selenium/webdriver/remote/webdriver.py",
line 321, in execute
    self.error_handler.check_response(response)
  File
"/home/bradley/venv/lib64/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py",
line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out
receiving message from renderer: -0.001
  (Session info: headless chrome=80.0.3987.132)

2020-04-23 18:35:30.854588 [86922] Starting up 12 parallel browser sessions.
2020-04-23 18:45:31.556583 [86922] Unhandled exception occurred during
testing sequence
2020-04-23 18:45:31.556645 [86922] Finished Running Testing Sequence!
======== TASK PROCESS RESULT START ========
{"success": false}
======== TASK PROCESS RESULT END ========
2020-04-23 18:45:31.689192 [76944] Terminating task subprocess, task
finished.
2020-04-23 18:45:32.733031 [76944] Task Subprocess finished and gave back
result
{
    "success": false
}
Traceback (most recent call last):
  File
"/home/bradley/venv/lib64/python3.7/site-packages/kwola/tasks/RunTestingStep.py",
line 117, in runTestingStep
    environment = WebEnvironment(config=config)
  File
"/home/bradley/venv/lib64/python3.7/site-packages/kwola/components/environments/WebEnvironment.py",
line 63, in __init__
    future.result() for future in sessionFutures
  File
"/home/bradley/venv/lib64/python3.7/site-packages/kwola/components/environments/WebEnvironment.py",
line 63, in <listcomp>
    future.result() for future in sessionFutures
  File "/usr/lib64/python3.7/concurrent/futures/_base.py", line 435, in
result
    return self.__get_result()
  File "/usr/lib64/python3.7/concurrent/futures/_base.py", line 384, in
__get_result
    raise self._exception
  File "/usr/lib64/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File
"/home/bradley/venv/lib64/python3.7/site-packages/kwola/components/environments/WebEnvironment.py",
line 49, in createSession
    return WebEnvironmentSession(config, number, self.proxyPort,
self.pathTracer)
  File
"/home/bradley/venv/lib64/python3.7/site-packages/kwola/components/environments/WebEnvironmentSession.py",
line 77, in __init__
    self.driver.get(self.targetURL)
  File
"/home/bradley/venv/lib64/python3.7/site-packages/selenium/webdriver/remote/webdriver.py",
line 333, in get
    self.execute(Command.GET, {'url': url})
  File
"/home/bradley/venv/lib64/python3.7/site-packages/selenium/webdriver/remote/webdriver.py",
line 321, in execute
    self.error_handler.check_response(response)
  File
"/home/bradley/venv/lib64/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py",
line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out
receiving message from renderer: -0.001
  (Session info: headless chrome=80.0.3987.132)

2020-04-23 18:35:33.792360 [87905] Starting up 12 parallel browser sessions.
2020-04-23 18:45:34.492580 [87905] Unhandled exception occurred during
testing sequence
2020-04-23 18:45:34.492640 [87905] Finished Running Testing Sequence!
======== TASK PROCESS RESULT START ========
{"success": false}
======== TASK PROCESS RESULT END ========
2020-04-23 18:45:34.506907 [76944] Terminating task subprocess, task
finished.
2020-04-23 18:45:35.728994 [76944] Task Subprocess finished and gave back
result
{
    "success": false
}
Traceback (most recent call last):
  File
"/home/bradley/venv/lib64/python3.7/site-packages/kwola/tasks/RunTestingStep.py",
line 117, in runTestingStep
    environment = WebEnvironment(config=config)
  File
"/home/bradley/venv/lib64/python3.7/site-packages/kwola/components/environments/WebEnvironment.py",
line 63, in __init__
    future.result() for future in sessionFutures
  File
"/home/bradley/venv/lib64/python3.7/site-packages/kwola/components/environments/WebEnvironment.py",
line 63, in <listcomp>
    future.result() for future in sessionFutures
  File "/usr/lib64/python3.7/concurrent/futures/_base.py", line 435, in
result
    return self.__get_result()
  File "/usr/lib64/python3.7/concurrent/futures/_base.py", line 384, in
__get_result
    raise self._exception
  File "/usr/lib64/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File
"/home/bradley/venv/lib64/python3.7/site-packages/kwola/components/environments/WebEnvironment.py",
line 49, in createSession
    return WebEnvironmentSession(config, number, self.proxyPort,
self.pathTracer)
  File
"/home/bradley/venv/lib64/python3.7/site-packages/kwola/components/environments/WebEnvironmentSession.py",
line 77, in __init__
    self.driver.get(self.targetURL)
  File
"/home/bradley/venv/lib64/python3.7/site-packages/selenium/webdriver/remote/webdriver.py",
line 333, in get
    self.execute(Command.GET, {'url': url})
  File
"/home/bradley/venv/lib64/python3.7/site-packages/selenium/webdriver/remote/webdriver.py",
line 321, in execute
    self.error_handler.check_response(response)
  File
"/home/bradley/venv/lib64/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py",
line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out
receiving message from renderer: -0.001
  (Session info: headless chrome=80.0.3987.132)

2020-04-23 18:45:38.547028 [76944] Task Subprocess finished and gave back
result
{
    "success": false
}
2020-04-23 18:35:36.821550 [88789] Starting up 12 parallel browser sessions.
2020-04-23 18:45:38.510266 [88789] Unhandled exception occurred during
testing sequence
2020-04-23 18:45:38.510328 [88789] Finished Running Testing Sequence!
======== TASK PROCESS RESULT START ========
{"success": false}
======== TASK PROCESS RESULT END ========
2020-04-23 18:45:38.699133 [76944] Terminating task subprocess, task
finished.
2020-04-23 18:45:42.742679 [76944] Task Subprocess finished and gave back
result
{
    "success": false
}
Traceback (most recent call last):
  File "/home/bradley/venv/bin/kwola", line 8, in <module>
    sys.exit(main())
  File
"/home/bradley/venv/lib64/python3.7/site-packages/kwola/bin/main.py", line
181, in main
    TrainAgentLoop.trainAgent(configDir)
  File
"/home/bradley/venv/lib64/python3.7/site-packages/kwola/tasks/TrainAgentLoop.py",
line 256, in trainAgent
    runRandomInitialization(config, trainingSequence, exitOnFail=True)
  File
"/home/bradley/venv/lib64/python3.7/site-packages/kwola/tasks/TrainAgentLoop.py",
line 82, in runRandomInitialization
    raise RuntimeError("Random initialization sequence failed and did not
return a result.")
RuntimeError: Random initialization sequence failed and did not return a
result.
(venv) [bradley@therig ~]$ https://s.app.joinlane.com/login^C
(venv) [bradley@therig ~]$
